#!/bin/sh

# This script generates and pushes the build VM bundle on the build machine.

set -e

if [ -z "$1" ]; then
    echo "Usage: $0 <ip>"
    exit 1
fi

./buildvmbundle
ssh root@$1 rm -rf /teambox
scp -r bundle root@$1:/teambox
rm -rf bundle

